# Generated by Django 5.1.6 on 2025-03-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infoextra',
            name='workplace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
