# Generated by Django 5.1.6 on 2025-03-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img_cover',
            field=models.ImageField(blank=True, null=True, upload_to='blogs'),
        ),
    ]
