# Generated by Django 5.1.6 on 2025-03-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_img_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img_cover',
            field=models.ImageField(blank=True, null=True, upload_to='blogs_images/'),
        ),
    ]
